#![allow(clippy::doc_overindented_list_items)]

pub mod helpers;

// Include the generated protobuf code.
// The file name generated by prost depends on the `package` directive in onnx.proto.
// Assuming it is `package onnx;`, the file will be `onnx.rs`.
include!(concat!(env!("OUT_DIR"), "/onnx.rs"));
